# Generated by Django 4.1.7 on 2023-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0002_alter_userdetail_firstname_alter_userdetail_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='facebookID',
            field=models.CharField(max_length=100, null=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='googleID',
            field=models.CharField(max_length=100, null=True, verbose_name='Google ID'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_ID',
            field=models.CharField(max_length=100, null=True, verbose_name='User ID'),
        ),
    ]
