# Generated by Django 4.1.7 on 2023-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0004_remove_profile_intrest_profile_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionDuration',
            field=models.CharField(max_length=500, null=True, verbose_name='Subscription Durations'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionType',
            field=models.CharField(max_length=500, null=True, verbose_name='Subscription Type'),
        ),
    ]
