# Generated by Django 4.1.7 on 2023-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0006_alter_movie_movieduration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='seriesCast',
        ),
        migrations.AddField(
            model_name='series',
            name='seriesCast',
            field=models.ManyToManyField(default=None, null=True, related_name='seriesCast', to='OTT.cast', verbose_name='Cast'),
        ),
    ]
