# Generated by Django 4.1.7 on 2023-04-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0007_remove_series_seriescast_series_seriescast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='seriesCast',
            field=models.ManyToManyField(default=None, related_name='seriesCast', to='OTT.cast', verbose_name='Cast'),
        ),
    ]
