# Generated by Django 4.1.7 on 2023-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0009_alter_series_seriescast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episodePublishType',
            field=models.CharField(max_length=5, null=True, verbose_name='Episode Publish Type'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_is_for18Plus',
            field=models.CharField(max_length=3, null=True, verbose_name='Episode is for 18+'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='laterEpisodeDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='laterEpisodeTime',
            field=models.TimeField(default=None, null=True),
        ),
    ]
