# Generated by Django 4.1.7 on 2023-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0010_alter_episode_episodepublishtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episodeDuration',
            field=models.CharField(max_length=50, null=True, verbose_name='Episode Durations'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeLink_1080p',
            field=models.CharField(max_length=500, null=True, verbose_name='Episode Link 1080p'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeLink_360p',
            field=models.CharField(max_length=500, null=True, verbose_name='Episode Link 360p'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeLink_480p',
            field=models.CharField(max_length=500, null=True, verbose_name='Episode Link 480p'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeLink_720p',
            field=models.CharField(max_length=500, null=True, verbose_name='Episode Link 720p'),
        ),
    ]
