# Generated by Django 4.1.7 on 2023-04-03 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTT', '0011_alter_episode_episodeduration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='mainUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Main User'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='profileID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OTT.profile', verbose_name='Profile Name'),
        ),
    ]
