# Generated by Django 4.1.7 on 2023-04-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0012_alter_wishlist_mainuser_alter_wishlist_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='mainUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OTT.userdetail', verbose_name='Main User'),
        ),
    ]
