# Generated by Django 4.1.7 on 2023-04-04 09:04

import OTT.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0013_alter_wishlist_mainuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarName', models.CharField(max_length=100, null=True, verbose_name='Avatar Name')),
                ('avatraImage', models.FileField(blank=True, null=True, upload_to='OTT/static/image/avatar', validators=[OTT.validators.validate_file_extension_image], verbose_name='Avatar Images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
