# Generated by Django 4.1.7 on 2023-04-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0015_remove_profile_avtar_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatraImage',
            new_name='avatarImage',
        ),
    ]
