# Generated by Django 4.1.7 on 2023-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0016_rename_avatraimage_avatar_avatarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='otpVerification',
            field=models.CharField(blank=True, default='no', max_length=3, null=True, verbose_name='OTP Verification'),
        ),
    ]
