# Generated by Django 4.1.7 on 2023-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0017_userdetail_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='otpVerificationTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Verification Time'),
        ),
    ]
