# Generated by Django 4.1.7 on 2023-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0018_userdetail_otpverificationtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='facebookID',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='googleID',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='deviceType',
            field=models.CharField(max_length=100, null=True, verbose_name='Device Type'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='devicelId',
            field=models.CharField(max_length=100, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='socialId',
            field=models.CharField(max_length=100, null=True, verbose_name='Social ID'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='socialType',
            field=models.CharField(max_length=100, null=True, verbose_name='Social Type'),
        ),
    ]
